# ipify-api server deployment for k8s
# author: tekintian@gmail.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipify-deployment
  namespace: default
  labels:
    name: ipify
    app: ipify-api
    version: "202202"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ipify
      app: ipify-api
      version: "202202"
  template:
    metadata:
      labels:
        name: ipify
        app: ipify-api
        version: "202202"
    spec:
      containers:
      - name: ipify
        image: tekintian/ipify-api:202202
        ports:
          - containerPort: 3000
            name: tcp
            protocol: TCP

---
# ipify-api service for Cluster IP
# Exposes the service on a cluster-internal IP. Choosing this value makes the service only reachable from within the cluster. This is the default type.
kind: Service
apiVersion: v1
metadata:
  name: ipify
  namespace: default
  labels:
    name: ipify
    app: ipify-api
    version: "202202"
spec:
  ports:
  - name: ipify-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: ipify
    app: ipify-api
    version: "202202"

---
# ipify-api service for Node Port
# Exposes the service on each node's IP at a static port (the `NodePort`). You'll be able to contact this type of service, from outside the cluster, by requesting `<NodeIP>:<NodePort>`.
apiVersion: v1
kind: Service
metadata:
  name: ipify-port
  namespace: default
spec:
  ports:
  - nodePort: 31003
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: ipify
    app: ipify-api
    version: "202202"
  type: NodePort
